filebeat.inputs:
- type: log
  enabled: true
  paths:
    - /logs/*.log
  json.keys_under_root: true
  json.overwrite_keys: true
  json.add_error_key: true

output.elasticsearch:
  hosts: ["aegis_elastic:9200"]
  username: "elastic"
  password: "changeme"

setup.kibana:
  host: "aegis_kibana:5601"
